using CommunityToolkit.Mvvm.ComponentModel;
using KCY_Accounting.Core.Models;

namespace KCY_Accounting.Core.ViewModels;

/// <summary>
/// Editable wrapper around a single FreightItem for use in the CarrierOrderEditView.
/// All computed properties (TotalWeightKg, VolumeCbm) update automatically via
/// partial methods generated by the CommunityToolkit.Mvvm source generator.
/// </summary>
public partial class FreightItemViewModel : ObservableObject
{
    [ObservableProperty] private int     _quantity        = 1;
    [ObservableProperty] private decimal? _lengthCm;
    [ObservableProperty] private decimal? _widthCm;
    [ObservableProperty] private decimal? _heightCm;
    [ObservableProperty] private decimal? _weightKgPerUnit;
    [ObservableProperty] private string   _description    = string.Empty;

    // Trigger computed property notifications whenever inputs change.
    // The 'value' parameter is required by the CommunityToolkit.Mvvm source generator contract.
#pragma warning disable IDE0060
    partial void OnQuantityChanged(int value)
    {
        OnPropertyChanged(nameof(TotalWeightKg));
        OnPropertyChanged(nameof(VolumeCbm));
    }
    partial void OnWeightKgPerUnitChanged(decimal? value) => OnPropertyChanged(nameof(TotalWeightKg));
    partial void OnLengthCmChanged(decimal? value)        => OnPropertyChanged(nameof(VolumeCbm));
    partial void OnWidthCmChanged(decimal? value)         => OnPropertyChanged(nameof(VolumeCbm));
    partial void OnHeightCmChanged(decimal? value)        => OnPropertyChanged(nameof(VolumeCbm));
#pragma warning restore IDE0060

    /// <summary>Total weight = Quantity x WeightKgPerUnit.</summary>
    public decimal TotalWeightKg => Quantity * (WeightKgPerUnit ?? 0m);

    /// <summary>Volume string in m3 calculated from L x W x H.</summary>
    public string VolumeCbm =>
        LengthCm.HasValue && WidthCm.HasValue && HeightCm.HasValue
            ? $"{Math.Round(Quantity * LengthCm.Value * WidthCm.Value * HeightCm.Value / 1_000_000m, 4):N4} m3"
            : "-";

    /// <summary>Convert this ViewModel back to the domain FreightItem for persistence.</summary>
    public FreightItem ToModel(int carrierOrderId = 0) => new()
    {
        CarrierOrderId  = carrierOrderId,
        Quantity        = Quantity,
        LengthCm        = LengthCm,
        WidthCm         = WidthCm,
        HeightCm        = HeightCm,
        WeightKgPerUnit = WeightKgPerUnit,
        Description     = Description
    };

    /// <summary>Create a ViewModel from an existing persisted FreightItem.</summary>
    public static FreightItemViewModel FromModel(FreightItem m) => new()
    {
        Quantity        = m.Quantity,
        LengthCm        = m.LengthCm,
        WidthCm         = m.WidthCm,
        HeightCm        = m.HeightCm,
        WeightKgPerUnit = m.WeightKgPerUnit,
        Description     = m.Description
    };
}

