using CommunityToolkit.Mvvm.ComponentModel;
using KCY_Accounting.Core.Models;

namespace KCY_Accounting.Core.ViewModels;

/// <summary>
/// Editable wrapper around a single FreightItem for use in the CarrierOrderEditView.
/// All computed properties (TotalWeightKg, VolumeCbm) update automatically via
/// partial methods generated by the CommunityToolkit.Mvvm source generator.
/// </summary>
public partial class FreightItemViewModel : ObservableObject
{
    [ObservableProperty] private int     _quantity        = 1;
    [ObservableProperty] private decimal? _lengthM;
    [ObservableProperty] private decimal? _widthM;
    [ObservableProperty] private decimal? _heightM;
    [ObservableProperty] private decimal? _weightKgPerUnit;
    [ObservableProperty] private string   _description    = string.Empty;

    // Trigger computed property notifications whenever inputs change.
    // The 'value' parameter is required by the CommunityToolkit.Mvvm source generator contract.
#pragma warning disable IDE0060
    partial void OnQuantityChanged(int value)
    {
        OnPropertyChanged(nameof(TotalWeightKg));
        OnPropertyChanged(nameof(VolumeCbm));
    }
    partial void OnWeightKgPerUnitChanged(decimal? value) => OnPropertyChanged(nameof(TotalWeightKg));
    partial void OnLengthMChanged(decimal? value)         => OnPropertyChanged(nameof(VolumeCbm));
    partial void OnWidthMChanged(decimal? value)          => OnPropertyChanged(nameof(VolumeCbm));
    partial void OnHeightMChanged(decimal? value)         => OnPropertyChanged(nameof(VolumeCbm));
#pragma warning restore IDE0060

    /// <summary>Total weight = Quantity x WeightKgPerUnit.</summary>
    public decimal TotalWeightKg => Quantity * (WeightKgPerUnit ?? 0m);

    /// <summary>Volume string in m³ calculated from L x W x H (all in metres).</summary>
    public string VolumeCbm =>
        LengthM.HasValue && WidthM.HasValue && HeightM.HasValue
            ? $"{Math.Round(Quantity * LengthM.Value * WidthM.Value * HeightM.Value, 4):N4} m³"
            : "-";

    /// <summary>Convert this ViewModel back to the domain FreightItem for persistence.</summary>
    public FreightItem ToModel(int carrierOrderId = 0) => new()
    {
        CarrierOrderId  = carrierOrderId,
        Quantity        = Quantity,
        LengthM         = LengthM,
        WidthM          = WidthM,
        HeightM         = HeightM,
        WeightKgPerUnit = WeightKgPerUnit,
        Description     = Description
    };

    /// <summary>Create a ViewModel from an existing persisted FreightItem.</summary>
    public static FreightItemViewModel FromModel(FreightItem m) => new()
    {
        Quantity        = m.Quantity,
        LengthM         = m.LengthM,
        WidthM          = m.WidthM,
        HeightM         = m.HeightM,
        WeightKgPerUnit = m.WeightKgPerUnit,
        Description     = m.Description
    };
}

